// <auto-generated />
using System;
using CafeJiji.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeJiji.Migrations
{
    [DbContext(typeof(CafeJijiDbContext))]
    partial class CafeJijiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CafeJiji.Models.Adotante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Adotantes");
                });

            modelBuilder.Entity("CafeJiji.Models.Gato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdotanteId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataAdotacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataChegada")
                        .HasColumnType("date");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroProtocoloONG")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdotanteId");

                    b.ToTable("Gatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataChegada = new DateOnly(2026, 4, 10),
                            FotoUrl = "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=500",
                            Nome = "Mingau",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            DataChegada = new DateOnly(2026, 5, 1),
                            FotoUrl = "https://images.unsplash.com/photo-1573865526739-10659fec78a5?q=80&w=500",
                            Nome = "Frajola",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            DataChegada = new DateOnly(2026, 3, 15),
                            FotoUrl = "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=500",
                            Nome = "Paçoca",
                            Status = 1
                        });
                });

            modelBuilder.Entity("CafeJiji.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeAtual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Insumos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstoqueMinimo = 2,
                            Nome = "Fardo Leite Integral (12L)",
                            QuantidadeAtual = 5
                        },
                        new
                        {
                            Id = 2,
                            EstoqueMinimo = 3,
                            Nome = "Café em Grãos Blend Especial (1kg)",
                            QuantidadeAtual = 8
                        });
                });

            modelBuilder.Entity("CafeJiji.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItensPedidos");
                });

            modelBuilder.Entity("CafeJiji.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("CafeJiji.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<bool>("RequerPreparo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(6939),
                            Categoria = "Cafés",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(6703),
                            EstoqueMinimo = 0,
                            Nome = "Espresso Tradicional",
                            Preco = 7.50m,
                            QuantidadeEstoque = 999,
                            RequerPreparo = true
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7106),
                            Categoria = "Cafés",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7105),
                            EstoqueMinimo = 0,
                            Nome = "Capuccino Gateiro",
                            Preco = 12.00m,
                            QuantidadeEstoque = 999,
                            RequerPreparo = true
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7107),
                            Categoria = "Cafés",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7107),
                            EstoqueMinimo = 0,
                            Nome = "Latte Macchiato",
                            Preco = 14.50m,
                            QuantidadeEstoque = 999,
                            RequerPreparo = true
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7109),
                            Categoria = "Doces",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7108),
                            EstoqueMinimo = 3,
                            Nome = "Fatia de Torta Holandesa",
                            Preco = 16.00m,
                            QuantidadeEstoque = 12,
                            RequerPreparo = false
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7110),
                            Categoria = "Doces",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7110),
                            EstoqueMinimo = 5,
                            Nome = "Brownie de Chocolate",
                            Preco = 9.50m,
                            QuantidadeEstoque = 20,
                            RequerPreparo = false
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7111),
                            Categoria = "Salgados",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7111),
                            EstoqueMinimo = 4,
                            Nome = "Pão de Queijo Recheado",
                            Preco = 8.00m,
                            QuantidadeEstoque = 15,
                            RequerPreparo = false
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7113),
                            Categoria = "Serviços",
                            CriadoEm = new DateTime(2026, 5, 20, 1, 49, 59, 943, DateTimeKind.Local).AddTicks(7112),
                            EstoqueMinimo = 0,
                            Nome = "Taxa de Entrada Gatil",
                            Preco = 15.00m,
                            QuantidadeEstoque = 9999,
                            RequerPreparo = false
                        });
                });

            modelBuilder.Entity("CafeJiji.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Kiki",
                            Perfil = "Gerente",
                            SenhaHash = "hash_senior_123",
                            Username = "jiji.senior"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Ursula",
                            Perfil = "Atendente",
                            SenhaHash = "hash_junior_123",
                            Username = "jiji.junior"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Osono",
                            Perfil = "Barista",
                            SenhaHash = "hash_pleno_123",
                            Username = "jiji.pleno"
                        });
                });

            modelBuilder.Entity("CafeJiji.Models.Gato", b =>
                {
                    b.HasOne("CafeJiji.Models.Adotante", "Adotante")
                        .WithMany()
                        .HasForeignKey("AdotanteId");

                    b.Navigation("Adotante");
                });

            modelBuilder.Entity("CafeJiji.Models.ItemPedido", b =>
                {
                    b.HasOne("CafeJiji.Models.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CafeJiji.Models.Pedido", b =>
                {
                    b.HasOne("CafeJiji.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CafeJiji.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
